# Generated by Django 5.2.8 on 2025-11-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="created_at",
        ),
    ]
