# Generated by Django 5.2.8 on 2025-11-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_alter_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='suno_task_id',
            field=models.CharField(blank=True, help_text='Suno 곡 생성 taskId', max_length=100, null=True, unique=True),
        ),
    ]
